include: package:pedantic/analysis_options.yaml

# For lint rules and documentation, see http://dart-lang.github.io/linter/lints.
# Uncomment to specify additional rules.
linter:
  rules:
  - camel_case_types
  - prefer_typing_uninitialized_variables
  - constant_identifier_names
  - library_names
  - file_names
  - library_prefixes
  - directives_ordering

analyzer:
#   exclude:
#     - path/to/excluded/files/**
