name: mdm_build
description: A web server built using the shelf package.
# version: 1.0.0
# homepage: https://www.example.com
# author: sunmh <email@example.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  args: ^1.4.2
  shelf: ^0.7.2
  common_utils: ^1.0.9
  mongo_dart: ^0.3.4

dev_dependencies:
  pedantic: ^1.0.0
