name: mdm_build
description: A web server built using the shelf package.
# version: 1.0.0
# homepage: https://www.example.com
# author: sunmh <email@example.com>

environment:
  sdk: '>=2.3.0 <3.0.0'

dependencies:
  args: ^1.6.0
  meta: ^1.2.1
  shelf: ^0.7.7
  common_utils: ^1.2.1
  mongo_dart: 0.4.0
  uuid: ^2.2.0
  dio: ^3.0.9
  image: ^2.1.14
  shell: 1.0.1
  xml: ^4.4.0
  mime: ^0.9.6
  mailer: ^3.0.4
  dartis: ^0.5.0

dev_dependencies:
  pedantic: ^1.0.0
